
#include <iostream>
#include "FL/Fl.H"
#include "FL/Fl_Window.H"
#include "FL/Fl_Menu.H"
#include "FL/Fl_Menu_Bar.H"
#include "FL/Fl_Box.H"
#include "FL/Fl_Button.H"
#include "FL/Fl_Group.H"
#include "FL/Fl_Input.H"
#include "FL/Fl_Secret_Input.H"
#include "FL/Fl_Float_Input.H"
#include "Fl/Fl_Text_Display.H"
#include "Head.h"
#include "Arm.h"
#include "Torso.h"
#include "Battery.h"
#include "Locomotor.h"
#include "RobotModel.h"
#include "RobotPart.h"
#include <vector>
#include <iomanip>
#include <iostream>
#include <string.h>
#include "../../../std_lib_facilities.h"